// Dữ liệu phim mẫu
const movies = [
    {
        id: 0,
        title: "Kết quả bài tập 30",
        year: 2026,
        genre: "Học tập",
        rating: 10.0,
        duration: "Không giới hạn",
        description: "Bài tập thực hành về chế độ sáng/tối (Light/Dark Mode) với CSS Variables và JavaScript. Bao gồm thiết kế 2 bảng màu, chuyển đổi theme, và giao diện người dùng hiện đại.",
        image: "images/anh000.jpg",
        trailer: "#",
        cast: ["Danh Trường Hưng", "GE04", "Frontend Developer"],
        director: "Bản thân"
    },
    {
        id: 1,
        title: "Avengers: Endgame",
        year: 2019,
        genre: "Hành động",
        rating: 8.4,
        duration: "3h 1m",
        description: "Sau sự kiện tàn khốc từ Hủy diệt, các Avengers còn sống phải tìm cách đảo ngược hành động của Thanos.",
        image: "images/anh011.jpg",
        trailer: "https://www.youtube.com/embed/TcMBFSGVi1c",
        cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"],
        director: "Anthony Russo, Joe Russo"
    },
    {
        id: 2,
        title: "Inception",
        year: 2010,
        genre: "Hành động",
        rating: 8.8,
        duration: "2h 28m",
        description: "Một đạo chích chuyên đánh cắp bí mật từ trong tiềm thức, được giao nhiệm vụ cài đặt một ý tưởng.",
        image: "images/anh012.jpg",
        trailer: "https://www.youtube.com/embed/YoHD9XEInc0",
        cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
        director: "Christopher Nolan"
    },
    {
        id: 3,
        title: "Interstellar",
        year: 2014,
        genre: "Viễn tưởng",
        rating: 8.6,
        duration: "2h 49m",
        description: "Một nhóm phi hành gia du hành qua một lỗ giun để cứu nhân loại khỏi nạn đói.",
        image: "images/anh013.jpg",
        trailer: "https://www.youtube.com/embed/zSWdZVtXT7E",
        cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
        director: "Christopher Nolan"
    },
    {
        id: 4,
        title: "The Dark Knight",
        year: 2008,
        genre: "Hành động",
        rating: 9.0,
        duration: "2h 32m",
        description: "Batman phải đối mặt với Joker, một thiên tài tội phạm điên loạn.",
        image: "images/anh014.jpg",
        trailer: "https://www.youtube.com/embed/EXeTwQWrcwY",
        cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
        director: "Christopher Nolan"
    },
    {
        id: 5,
        title: "Parasite",
        year: 2019,
        genre: "Tâm lý",
        rating: 8.6,
        duration: "2h 12m",
        description: "Câu chuyện về hai gia đình với hoàn cảnh sống trái ngược nhau.",
        image: "images/anh015.jpg",
        trailer: "https://www.youtube.com/embed/5xH0HfJHsaY",
        cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
        director: "Bong Joon-ho"
    },
    {
        id: 6,
        title: "The Matrix",
        year: 1999,
        genre: "Viễn tưởng",
        rating: 8.7,
        duration: "2h 16m",
        description: "Một hacker phát hiện ra sự thật về thực tại ảo và cuộc chiến chống lại nó.",
        image: "images/anh016.jpg",
        trailer: "https://www.youtube.com/embed/m8e-FFROxZM",
        cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
        director: "Lana Wachowski, Lilly Wachowski"
    },
    {
        id: 7,
        title: "The Godfather",
        year: 1972,
        genre: "Tội phạm",
        rating: 9.2,
        duration: "2h 55m",
        description: "Câu chuyện về gia đình Mafia Corleone và hành trình của Michael Corleone trở thành ông trùm.",
        image: "images/anh017.jpg",
        trailer: "https://www.youtube.com/embed/UaVTfg8m0I0",
        cast: ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall"],
        director: "Francis Ford Coppola"
    },
    {
        id: 8,
        title: "Pulp Fiction",
        year: 1994,
        genre: "Tội phạm",
        rating: 8.9,
        duration: "2h 34m",
        description: "Câu chuyện phi tuyến tính về các tay súng, võ sĩ đấm bốc và xã hội đen Los Angeles.",
        image: "images/anh018.jpg",
        trailer: "https://www.youtube.com/embed/s7EdQ4FqbhY",
        cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
        director: "Quentin Tarantino"
    },
    {
        id: 9,
        title: "Forrest Gump",
        year: 1994,
        genre: "Tình cảm",
        rating: 8.8,
        duration: "2h 22m",
        description: "Câu chuyện cảm động về Forrest Gump, một người đàn ông đơn giản nhưng đã sống qua nhiều biến cố lịch sử.",
        image: "images/anh019.jpg",
        trailer: "https://www.youtube.com/embed/bLvqoHBptjg",
        cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
        director: "Robert Zemeckis"
    },
    {
        id: 10,
        title: "The Shawshank Redemption",
        year: 1994,
        genre: "Tâm lý",
        rating: 9.3,
        duration: "2h 22m",
        description: "Câu chuyện về hy vọng và tình bạn trong nhà tù Shawshank.",
        image: "images/anh0110.jpg",
        trailer: "https://www.youtube.com/embed/6hB3S9bIaco",
        cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
        director: "Frank Darabont"
    },
    {
        id: 11,
        title: "Gladiator",
        year: 2000,
        genre: "Hành động",
        rating: 8.5,
        duration: "2h 35m",
        description: "Câu chuyện về Maximus, một vị tướng La Mã bị phản bội và trở thành đấu sĩ gladiator.",
        image: "images/anh0111.jpg",
        trailer: "https://www.youtube.com/embed/owK4WPEI3G4",
        cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen", "Oliver Reed"],
        director: "Ridley Scott"
    },
    {
        id: 12,
        title: "Titanic",
        year: 1997,
        genre: "Tình cảm",
        rating: 7.8,
        duration: "3h 14m",
        description: "Câu chuyện tình yêu giữa Jack và Rose trên chuyến tàu Titanic định mệnh.",
        image: "images/anh0112.jpg",
        trailer: "https://www.youtube.com/embed/2e-eXJ6HgkQ",
        cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates"],
        director: "James Cameron"
    },
    {
        id: 13,
        title: "Jurassic Park",
        year: 1993,
        genre: "Viễn tưởng",
        rating: 8.1,
        duration: "2h 7m",
        description: "Câu chuyện về công viên khủng long được tạo ra từ DNA hóa thạch.",
        image: "images/anh0113.jpg",
        trailer: "https://www.youtube.com/embed/QWBKEmWWL38",
        cast: ["Sam Neill", "Laura Dern", "Jeff Goldblum", "Richard Attenborough"],
        director: "Steven Spielberg"
    },
    {
        id: 14,
        title: "The Lion King",
        year: 1994,
        genre: "Hoạt hình",
        rating: 8.5,
        duration: "1h 58m",
        description: "Câu chuyện về Simba, chú sư tử con tìm lại vương quốc của mình.",
        image: "images/anh0114.jpg",
        trailer: "https://www.youtube.com/embed/4sj1Mf8c6g0",
        cast: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones", "Nathan Lane"],
        director: "Roger Allers, Rob Minkoff"
    },
    {
        id: 15,
        title: "Harry Potter and the Sorcerer's Stone",
        year: 2001,
        genre: "Viễn tưởng",
        rating: 7.6,
        duration: "2h 32m",
        description: "Câu chuyện về Harry Potter và hành trình vào thế giới phù thủy.",
        image: "images/anh0115.jpg",
        trailer: "https://www.youtube.com/embed/VyHV0BRtdxo",
        cast: ["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Richard Harris"],
        director: "Chris Columbus"
    }
];

// Dữ liệu thể loại
const genres = ["Tất cả", "Hành động", "Viễn tưởng", "Tâm lý", "Hài", "Kinh dị", "Tình cảm"];